Debug
=====

Allows to debug the application on runtime

To use application debugging you might need to install an emulator which
supports the `$420E` register to listen to debug commands.

Also you need to create the symbol file using the `-s <file>` argument when
compiling the source code, otherwise the commands won't be exported.

One emulator which supports the debug interface is the modified version
of https://github.com/BenjaminSchulte/bsnes-plus[bsnes-plus]. You need to
start the application with the `--enable-debug-interface` argument.

To enable debugging call `Debug.enable` at the start of your application.

[source,ruby]
----
Debug.enable

def main
  Debug.log "Hello world from debugger"

loop:
  BRA loop
end
----

== Methods

=== Debug

[[debug-brk]]
==== `Debug.BRK`

Adds a BRK operator (only in debug mode)

[[debug-enable]]
==== `Debug.enable`

Enables debugging

This needs to be called somewhere need to the start of the application

[[debug-log]]
==== `Debug.log(message, level=:info)`
* `message` string - the message which should be logged
* `level` string - one of `trace`, `debug`, `info`, `warn`, `error` or `fatal`

Logs a message to the emulator

This feature is not supported by all emulators

[[debug-only]]
==== `Debug.only`

Invokes the code inside the block only in debug mode

[source,ruby]
----
Debug.only do
  JSR debug_screen
end
----